### ISSUE TITLE
Empty selections shouldn't error with `allow_rename = FALSE`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tidyselect#221] opened 2020-11-04 14:55 UTC
``` r
tidyselect::eval_select(character(), mtcars, allow_rename = TRUE)
#> named integer(0)

tidyselect::eval_select(character(), mtcars, allow_rename = FALSE)
#> Error: Can't rename variables in this context.
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by eutwt** [comment] 2021-08-22 23:14
Would adding  `&& length(pos) > 0` to the `ensure_named` check as below cause problems elsewhere? It seems like that would be a simple way to close this issue.

``` r
ensure_named <- function(pos, vars, uniquely_named, allow_rename) {
  if (!allow_rename) {
    if (is_named(pos) && length(pos) > 0) {
      abort("Can't rename variables in this context.")
    }
    return(set_names(pos, NULL))
  }
...
```

**Comment by DavisVaughan** [comment] 2021-08-23 14:02
Slightly more rlang like would be `is_named(pos) && !is_empty(pos)` (same idea though).

I do think that would fix it, since the main issue is how `is_named()` treats empty named vectors vs vectors with `""` names.

``` r
library(rlang)

x <- character()
y <- "mpg"

tidyselect::eval_select(x, mtcars, allow_rename = FALSE)
#> Error: Can't rename variables in this context.
tidyselect::eval_select(y, mtcars, allow_rename = FALSE)
#> [1] 1

# Why are the above two different?
# Internally this is done to both
x <- set_names(x, names2(x))
y <- set_names(y, names2(y))

# empty, but named
x
#> named character(0)

# only "" names, which we don't interpret as being "named" in `is_named()`
y
#>       
#> "mpg"

rlang::is_named(x)
#> [1] TRUE
rlang::is_named(y)
#> [1] FALSE
```

**Comment by eutwt** [comment] 2021-08-23 16:32
Yeah. The issue is that the names vector of `x` doesn't have any invalid elements (`is.na` or ` == ""`). It's just a length-0 vector. Its indistinguishable from a properly-named vector that's been emptied. So I think it's reasonable for `rlang` to say that `x` is a named vector.

``` r
a <- setNames('a', 'a')[0]
names(a)
#> character(0)
b <- setNames('b', '')[0]
names(b)
#> character(0)
identical(names(a), names(b))
#> [1] TRUE
```

<sup>Created on 2021-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

 It's just that within the logic of `eval_select`, having a named empty vector doesn't imply the user is trying to rename variables. It wasn't named by the user, it's only named because it was passed to `named` by `loc_validate`.

**Closed** 2022-08-11 16:47 UTC
Labels: bug
