### ISSUE TITLE
Unclear error message with function that doesn't take arguments or returns wrong value

### ISSUE THREAD

**Issue by krlmlr** [r-lib/tidyselect#175] opened 2020-02-22 16:44 UTC
``` r
library(tidyselect)
library(rlang)

eval_select(quo(as.logical), set_names(letters))
#> named integer(0)
eval_select(quo(identity), set_names(letters))
#> Error: Can't coerce element 1 from a character to a logical
eval_select(quo(date), set_names(letters))
#> Error: unused argument (.x[[i]])
```

<sup>Created on 2020-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would expect messages like

-  "`identity()` doesn't return a logical vector, and there is no column/element/... `identity`".
-  "`date()` is a function that doesn't take arguments, and there is no column/element/... `date`".

Related: #162.

**Comment by lionel-** [comment] 2020-02-23 11:24
Agreed we should check the return type of functions and have tailored messages.

We shouldn't mention anything about columns though, since that behaviour is being deprecated.

**Comment by hadley** [comment] 2020-04-23 20:41
Now duplicate of #190

**Closed by hadley** 2020-04-23 20:41 UTC
