### ISSUE TITLE
Select unable to use glue output

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/tidyselect#176] opened 2020-02-23 18:00 UTC
There was a regression between tidyselect 0.2.5 and 1.0.0

In 0.2.5 this was possible

```
require(dplyr)
require(glue)
a = "foo"
b = "bar"
data.frame(foo_bar = 1:5) %>% select(glue("{a}_{b}"))
```

but now throws an error:

```
Error: Must subset columns with a valid subscript vector.
x The subscript has the wrong type `glue`.
ℹ It must be numeric or character.
Run `rlang::last_error()` to see where the error occurred.
```

Is it desirable to cast the output of glue via `as.character`?

**Comment by lionel-** [comment] 2020-02-24 09:44
Duplicate of #174.

Please install the dev version of glue:

```r
remotes::install_github("tidyverse/glue")
```

It should be released to CRAN this week.

**Closed by lionel-** 2020-02-24 09:44 UTC
