### ISSUE TITLE
Selecting the same variable twice with different names

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/tidyselect#59] opened 2018-04-12 06:25 UTC
``` r
tidyselect::vars_select( names(iris), a = Species, b = Species)
#>         b 
#> "Species"
```

originally in https://github.com/tidyverse/dplyr/issues/3499

**Comment by krlmlr** [comment] 2018-07-14 22:14
I'm not sure `select()` should duplicate columns.

**Comment by VincentGuyader** [comment] 2018-10-09 07:43
@krlmlr dont remember the use case :)
In my view select should duplicate the columns. Or at least return a warning in this case.

Regards

**Comment by lionel-** [comment] 2019-09-09 13:51
Duplicate of #52.

**Closed by lionel-** 2019-09-09 13:51 UTC
