### ISSUE TITLE
Error in combine_vars(vars, ind_list) : Position must be between 0 and n

### ISSUE THREAD

**Issue by LoriMoore** [r-lib/tidyselect#57] opened 2018-03-29 17:40 UTC
When trying to convert gbif objects to a data frame for the creation of a species distribution model, I receive the following error in **: 

```r
nv<-as.data.frame(nv$`Neovison vison`$data)%>%dplyr::select(1,3,4,34)%>%na.omit%>%
  dplyr::rename(Species=name,Y=decimalLatitude,X=decimalLongitude,Year=year)

#> Error in combine_vars(vars, ind_list) : Position must be between 0 and n
```

The script above these two lines works fine and I have installed these packages:
library(biomod2)
library(ecospat)
library(rgbif)
library(ggmap)
library(raster)       
library(sp)           
library(rgdal)        
library(rgeos)        
library(maptools)     
library(stringr)      
library(tidyverse)
library(reshape2)
library(dismo)
library(ade4)
library(cluster)
library(usdm)
library(rasterVis)

I am not sure how to resolve this and would hugely appreciate any help. Thank you!

**Comment by anujs5586** [comment] 2019-03-14 12:48
can somebody answer this please?

**Comment by lionel-** [comment] 2019-03-18 14:35
We'll work on a tidyselect release next month.

**Comment by anujs5586** [comment] 2019-03-22 11:05
Thanks.

Regards,
Anuj Sharma

**Comment by lionel-** [comment] 2019-09-09 13:49
Sorry for getting this long to get back to this.

I can only guess what's happening since you have not provided a reproducible example, but the error may be because `34` is too large a number for this data frame. How many columns did it have?

In any case, we should improve the error message.

**Comment by lionel-** [comment] 2019-09-09 13:50
Duplicate of #64.

**Closed by lionel-** 2019-09-09 13:50 UTC
Labels: ui:errors

**Comment by Nancy754** [comment] 2020-01-30 10:45
I am also having the same error message..
I have a dataset with 42 variables named V1to V42, I would like to use the select function under tidyverse library but I cant I keep getting the same error message.
My code reads :  rea<- select(data, 2:7) to select the the second to the 6th column
