### ISSUE TITLE
# Problem in lavaan, R programming

### ISSUE THREAD

**Issue by aliabidnefu** [r-lib/tidyselect#191] opened 2020-04-26 03:26 UTC
Hi, in this morning i run the confirmatory factor analysis in lavaan. After assigning latent variable, exogenous variable, variance and covariance, when i run the CFA, it show some problem as under:-
### > fit<-lavaan(tpb_model, data=baisalamtpb)

Error: Must extract column with a single valid subscript.
x The subscript `var.idx[i]` can't be `NA`.
Run `rlang::last_error()` to see where the error occurred.

Here are the whole factors :-
> tpb_model <- '
+ bi =~ attitude + sn + pbc
+ attitude =~ farm_sustainability + food_security + farm_production + farm_revenues + agri_inputs
+ sn =~ prefer_baisalam + think_baisalam + favor_baisalam
+ pbc =~ control_decision + financial_capability
+ # residual variance observed variables
+ farm_sustainability ~~ farm_sustainability
+ food_security ~~ food_security
+ farm_production ~~ farm_production
+ farm_revenues ~~ farm_revenues
+ agri_inputs ~~ agri_inputs
+ prefer_baisalam ~~ prefer_baisalam
+ think_baisalam ~~ think_baisalam
+ favor_baisalam ~~ favor_baisalam
+ control_decision ~~ control_decision
+ financial_capability ~~ financial_capability
+ # factor variances
+ attitude ~~ attitude
+ sn ~~ sn
+ pbc ~~ pbc
+ bi ~~ bi
+ # factor covariances
+ bi ~~ attitude + sn + pbc
+ attitude ~~ pbc + sn
+ sn ~~ pbc + att
+ attitude ~~ sn
+ attitude ~~ pbc
+ sn ~~ pbc'

**Comment by lionel-** [comment] 2020-04-26 06:11
The backtrace of `rlang::last_error()` would be useful to figure it out. A small reprex would be great, otherwise we can't help you.

I would recommend filing an issue in the lavaan repo though. It's unlikely a tidyselect problem.

**Comment by aliabidnefu** [comment] 2020-04-26 06:21
> rlang::last_error()
<error/vctrs_error_subscript_type>
Must extract column with a single valid subscript.
x The subscript `var.idx[i]` can't be `NA`.
Backtrace:
  1. lavaan::lavaan(tpb_model, data = baisalamnew)
  2. lavaan:::lav_dataframe_check_ordered(frame = data, ov.names = ov.names.y)
  4. tibble:::`[[.tbl_df`(frame, var.idx[i])
  5. tibble:::tbl_subset2(x, j = i, j_arg = substitute(i))
  6. tibble:::vectbl_as_col_location2(j, length(x), names(x), j_arg = j_arg)
 13. vctrs::vec_as_location2(i, n, names, arg = as_label(j_arg))
 14. vctrs:::result_get(...)
Run `rlang::last_trace()` to see the full context.

**Comment by aliabidnefu** [comment] 2020-04-26 06:24
> rlang::last_trace()
<error/vctrs_error_subscript_type>
Must extract column with a single valid subscript.
x The subscript `var.idx[i]` can't be `NA`.
Backtrace:
     █
  1. └─lavaan::lavaan(tpb_model, data = baisalamnew)
  2.   └─lavaan:::lav_dataframe_check_ordered(frame = data, ov.names = ov.names.y)
  3.     ├─frame[[var.idx[i]]]
  4.     └─tibble:::`[[.tbl_df`(frame, var.idx[i])
  5.       └─tibble:::tbl_subset2(x, j = i, j_arg = substitute(i))
  6.         └─tibble:::vectbl_as_col_location2(j, length(x), names(x), j_arg = j_arg)
  7.           ├─tibble:::subclass_col_index_errors(...)
  8.           │ ├─base::tryCatch(...)
  9.           │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
 10.           │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11.           │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
 12.           │ └─base::force(expr)
 13.           └─vctrs::vec_as_location2(i, n, names, arg = as_label(j_arg))
 14.             └─vctrs:::result_get(...)

**Comment by lionel-** [comment] 2020-04-26 08:25
Does the problem go away when you run this?

```r
baisalamnew_df <- as.data.frame(baisalamnew)
lavaan::lavaan(tpb_model, data = baisalamnew_df)
```

**Comment by lionel-** [comment] 2020-04-26 08:37
I think the problem is that `tibble()` has gotten stricter since version 3.0. https://www.tidyverse.org/blog/2020/04/tibble-3-0-0/

```r
tibble::tibble(x = 1)[[NA]]
#> Error: Must extract column with a single valid subscript.
#> ✖ Subscript `NA` can't be `NA`.

data.frame(x = 1)[[NA]]
#> NULL
```

If this analysis is correct, the author of lavaan should probably call `as.data.frame()` on its input to make sure it behaves like a base data frame.

**Comment by aliabidnefu** [comment] 2020-04-27 01:26
Thank you dear Dr. Lionel for your time.
According to your argument "Does the problem go away when you run this?"

yes its still the same:
> library(tibble)> as_tibble(baisalamtpb)
# A tibble: 233 x 14
   farm_sustainabi… food_security farm_production farm_revenues agri_inputs
              <dbl>         <dbl>           <dbl>         <dbl>       <dbl>
 1                6             5               8             8           6
 2                6             8               8             6           6
 3                8             8               8             6           8
 4                6             5               6             6           5
 5                8             8               5             6           5
 6                2             6               6             2           6
 7                5             5               3             6           6
 8                4             3               5             5           5
 9                5             8               6             6           6
10                6             6               5             3          -2
# … with 223 more rows, and 9 more variables: prefer_baisalam <dbl>,
#   think_baisalam <dbl>, favor_baisalam <dbl>, control_decision <dbl>,
#   financial_capability <dbl>, attitude <dbl>, sn <dbl>, pbc <dbl>, bi <dbl>


> baisalamnew_df <- as_tibble(baisalamtpb)
> lavaan::lavaan(tpb_model, data = baisalamnew_df)
Error: Must extract column with a single valid subscript.
x The subscript `var.idx[i]` can't be `NA`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by aliabidnefu** [comment] 2020-04-27 01:34
Thank you so much dear Dr. Iionel for precious time. as for as your first comment, "Does the problem go away when you run this?" its still have same. Since I am beginner, I am learning about "tibble", and hope this problem will be overcome.

> library(tibble)
> as_tibble(baisalamtpb)
A tibble: 233 x 14
   farm_sustainabi… food_security farm_production farm_revenues agri_inputs
              <dbl>         <dbl>           <dbl>         <dbl>       <dbl>
 1                6             5               8             8           6
 2                6             8               8             6           6
 3                8             8               8             6           8
 4                6             5               6             6           5
 5                8             8               5             6           5
 6                2             6               6             2           6
 7                5             5               3             6           6
 8                4             3               5             5           5
 9                5             8               6             6           6
10                6             6               5             3          -2
 … with 223 more rows, and 9 more variables: prefer_baisalam <dbl>,
 think_baisalam <dbl>, favor_baisalam <dbl>, control_decision <dbl>,
financial_capability <dbl>, attitude <dbl>, sn <dbl>, pbc <dbl>, bi <dbl>

> baisalamnew_df <- as_tibble(baisalamtpb)
> lavaan::lavaan(tpb_model, data = baisalamnew_df)

Error: Must extract column with a single valid subscript.
x The subscript `var.idx[i]` can't be `NA`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by aliabidnefu** [comment] 2020-04-27 03:27
Even, when I convert into factors, it also shows error:

> df <- data.frame(baisalamtpb)
> str(df)
'data.frame':	233 obs. of  14 variables:
 $ farm_sustainability : num  6 6 8 6 8 2 5 4 5 6 ...
 $ food_security       : num  5 8 8 5 8 6 5 3 8 6 ...
 $ farm_production     : num  8 8 8 6 5 6 3 5 6 5 ...
 $ farm_revenues       : num  8 6 6 6 6 2 6 5 6 3 ...
 $ agri_inputs         : num  6 6 8 5 5 6 6 5 6 -2 ...
 $ prefer_baisalam     : num  4 6 8 4 4 6 4.5 4.5 4 3 ...
 $ think_baisalam      : num  6 6 8 6 4 4.5 3 4.5 4 4.5 ...
 $ favor_baisalam      : num  6 6 8 6 6 6 3 6 4.5 1 ...
 $ control_decision    : num  6 1 8 4.5 8 4.5 8 3 6 3 ...
 $ financial_capability: num  8 0.5 8 8 6 6 3 4.5 3 4.5 ...
 $ attitude            : num  2.75 2.5 4 3.75 3.75 3.5 3.75 3.5 3.5 4 ...
 $ sn                  : num  4 3 4 3 4 4 3 2 2 2.5 ...
 $ pbc                 : num  2.5 1.5 4 2.5 3.5 4 3.5 2.5 3.5 2.5 ...
 $ bi                  : num  3.33 2.33 3.67 2.67 3.33 ...

> baisalamnew_df <- data.frame(baisalamtpb)
> lavaan::lavaan(tpb_model, data = baisalamnew_df)
Error in lav_data_full(data = data, group = group, cluster = cluster,  : 
  lavaan ERROR: missing observed variables in dataset: att

**Comment by lionel-** [comment] 2020-04-27 06:37
In the first snippet you have used `as_tibble()` instead of `as.data.frame()`. The problem is that tibble is stricter, so you really have to pass a data frame to lavaan, not a tibble.

In the second, where you're creating a data frame, you're getting a different error:

```
lavaan ERROR: missing observed variables in dataset: att
```

This does not look like a bug. It seems it's a user error that you should be able to fix, so we can close this issue.

**Closed by lionel-** 2020-04-27 06:37 UTC

**Comment by lionel-** [comment] 2020-04-27 06:41
I have notified the author of lavaan of the problem with tibbles: https://github.com/yrosseel/lavaan/issues/175

**Comment by TDJorgensen** [comment] 2020-04-27 07:12
The development version of lavaan already uses `as.data.frame()`: [yrosseel/lavaan/#163](https://github.com/yrosseel/lavaan/issues/163)
Hopefully this will cut down on future confusion for users unfamiliar with lack-of-inheritance issues in the tidyverse.
