### ISSUE TITLE
Optionally forbid selection by position ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/tidyselect#261] opened 2022-05-10 17:18 UTC
If I have a set of items in a context where order is meaningless, or ambiguous/misleading, like for instance in an environment, would there be a way to prevent the user to select by position ?

``` r
env <- as.environment(mtcars)

# I want this to work
tidyselect::vars_select(ls(env), matches("a"))
#>     am   carb   drat   gear 
#>   "am" "carb" "drat" "gear"

# I don't want this to work
tidyselect::vars_select(ls(env), 1)
#>   am 
#> "am"
```

<sup>Created on 2022-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Given that ultimately tidy selection converts the selection inputs to integer I'm not sure how to currently hijack the inputs and check if they're "true" integers and not a tidy selection.

**Comment by markfairbanks** [comment] 2022-05-10 18:44
Here's a workaround. You can test if expressions captured by `enexprs`/`enquos` are numeric values with `is.numeric`. This also works with character/logical/null values. Using that you can filter out the numeric selections and pass the rest to `var_select`.

``` r
library(rlang)
library(tidyselect)
library(purrr)

# Testing if an expression is a simple number
is.numeric(substitute(1))
#> [1] TRUE

is.numeric(substitute(matches("a")))
#> [1] FALSE

my_vars_select <- function(.vars, ...) {
  dots <- enquos(...)
  numeric_selection <- map_lgl(dots, ~ is.numeric(get_expr(.x)))
  dots <- dots[!numeric_selection]
  vars_select(.vars, !!!dots)
}

env <- as.environment(mtcars)

my_vars_select(ls(env), matches("a"))
#>     am   carb   drat   gear 
#>   "am" "carb" "drat" "gear"

my_vars_select(ls(env), 1)
#> named character(0)
```

**Comment by moodymudskipper** [comment] 2022-05-12 12:23
Thanks @markfairbanks but this would work only on very limited cases `my_vars_select(ls(env), 1+1)` for example is enough to break it. I now realised the `:` operator is also problematic when order is meaningless.

The following works, but might cause some dot args to be evaluated twice.

``` r
my_vars_select <- function(.vars, ...) {
  dots <- rlang::enquos(...)
  has_colon <- function(x) list(quote(`:`)) %in% as.list(rlang::quo_squash(x))
  some_dot_args_use_colon_op <- Position(has_colon, dots, nomatch = 0) > 0
  if (some_dot_args_use_colon_op) rlang::abort("Variables in environments have no order nor index")
  
  dot_values_no_tidyselect <- sapply(dots, function(x) try(rlang::eval_tidy(x), silent = TRUE))
  some_dot_args_eval_to_num <- Position(is.numeric, dot_values_no_tidyselect, nomatch = 0) > 0
  if (some_dot_args_eval_to_num)  rlang::abort("Variables in environments have no order nor index")
  tidyselect::vars_select(.vars, ...)
}

env <- as.environment(mtcars)

my_vars_select(ls(env), matches("a"))
#>     am   carb   drat   gear 
#>   "am" "carb" "drat" "gear"

my_vars_select(ls(env), 1+1)
#> Error in `my_vars_select()`:
#> ! Variables in environments have no order nor index

my_vars_select(ls(env), card:disp)
#> Error in `my_vars_select()`:
#> ! Variables in environments have no order nor index
```

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lionel-** [comment] 2022-05-12 14:38
The problem is that we can detect `1` but we can't reasonably detect expressions like `identity(1)` so I don't think tidyselect can provide that option.

**Comment by moodymudskipper** [comment] 2022-05-12 17:51
I think in theory we might have tidy selections have a contagious class that declares if they use item order, then if the argument is numeric and is not an "unordered_tidy_selection" this would fail. Or every `c()`, `&` etc could check that their arguments are not numerics that don't bear this class.

**Comment by lionel-** [comment] 2022-05-13 07:28
IIUC we'd have to rewrite existing helpers and make helper creation more complex. And it seems like this feature would have little payoff.

**Comment by moodymudskipper** [comment] 2022-05-13 08:16
Yes you understood correctly and you're probably right.

For context my true use case is that I'm playing with {rstudioapi} in a package where I'm opening/closing/saving tabs using tidy selection. At the moment {rstudioapi}  doesn't provide a notion of tab order, so a user who wants to select tab `1` or `this_tab:that_tab` might be surprised by the result and I have no robust way to warn them about it.

I've been enjoying how easy it is to extend tidy selection by creating custom helpers or applying it to other things than data frame and I think it might be underused in the community, this feature would broaden the perspectives. But I understand the cost benefit aspect and thanks for considering.

**Comment by lionel-** [comment] 2022-05-13 08:47
yup this is out of scope for tidyselect.

You could examine the expression supplied to you before evaluation with tidyselect, this way you could warn in common cases.

**Closed by lionel-** 2022-05-13 08:47 UTC
