### ISSUE TITLE
Support for lambda functions in `eval_select` (feature request)

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/tidyselect#181] opened 2020-03-20 17:35 UTC
With the incredible release of `tidyselect` v1.0.0, I met the awesome `eval_select` function.

I can now use functions to select columns for my package, which is a huge UX improvement.

I would like to be able to use lambda functions too, like in my last example:

```r
library(rlang)
library(tidyselect)
foo=function(...)
    enquos(...) %>% map(~eval_select(.x, iris)) %>% reduce(intersect)
foo(is.numeric | is.double, -Sepal.Width)
foo(is.numeric, is.double, -Sepal.Width)
foo(function(A) is.numeric(A), is.double, -Sepal.Width)
foo(as_function(~is.numeric(.x)), is.double, -Sepal.Width)
#this won't work
foo(~is.numeric(.x), is.double, -Sepal.Width) 
```

Wouldn't that be something worth considering?

**Comment by hadley** [comment] 2020-04-23 20:48
Now duplicate of #190

**Closed by hadley** 2020-04-23 20:48 UTC
