### ISSUE TITLE
Error: 'This tidyselect does not support predicates yet'

### ISSUE THREAD

**Issue by writetrevor** [r-lib/tidyselect#188] opened 2020-04-17 02:32 UTC
I downloaded the latest version of R-Studio, and am unable to use the map() function as I would typically do before I updated R Studio.  This is the error message:
Error: This tidyselect interface doesn't support predicates yet.
i Contact the package author and suggest using `eval_select()`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by lionel-** [comment] 2020-04-17 06:38
Please post information, we can't do anything based on just an error message. A reprex would be great https://reprex.tidyverse.org/

**Comment by writetrevor** [comment] 2020-04-17 17:41
Hello, 
Sorry for that. Is there any way I can remove the thread?
    On Friday, April 17, 2020, 01:38:41 AM CDT, Lionel Henry <notifications@github.com> wrote:  
 
 


Please post information, we can't do anything based on just an error message. A reprex would be great https://reprex.tidyverse.org/

**Comment by lionel-** [comment] 2020-04-18 05:07
No worries the thread is fine! I just need a small reproducible example of how to trigger the error.

**Comment by etiennebr** [comment] 2020-04-20 16:25
I'm going to speculate, because there aren't much details. But maybe the issue comes from the  error message when a column is not found, but there's an existing function in the environment.

```r
data.frame(average = 1:3) %>% dplyr::select(mean)
#' Error: This tidyselect interface doesn't support predicates yet.
#' ℹ Contact the package author and suggest using `eval_select()`.
```
The message can be confusing and the call to action might actually be over-the-top for a variable missing in the data frame.

**Comment by lionel-** [comment] 2020-04-20 18:42
We're probably going to review this UI to remove any ambiguity, before the dplyr 1.0 release.

**Comment by markfairbanks** [comment] 2020-04-22 17:40
Is the interface going to change or just the backend? For example - will `select(df, is.character)` still work, or is it going to become something like `select(df, pred(is.character))`?

**Comment by lionel-** [comment] 2020-04-22 18:25
Most likely more like the latter (which you can already emulate with `force(is.character)`. See context in https://github.com/tidyverse/dplyr/issues/5120

**Comment by hadley** [comment] 2020-04-23 20:41
Duplicate of #190

**Closed by hadley** 2020-04-23 20:41 UTC
