### ISSUE TITLE
export `where()`?

### ISSUE THREAD

**Issue by ddsjoberg** [r-lib/tidyselect#209] opened 2020-08-26 17:54 UTC
Would you consider exporting the `where()` function along with the others select helpers? Is there a reason it should not be exported?

I have a package that uses tidyselect to choose columns/set of columns, but in a nonstandard way, We use formula notation within arguments to assign characteristics to columns. For example, 

```r
library(gtsummary)

tbl_summary(
  df, 
  type = list(starts_with("con") ~ "continuous", 
              starts_with("cat") ~ "categorical") 
)
```

I run into an issue parsing the formulas as `where()` is not found. For the time being, I solved the issue by adding a copy of the `where()` function to the package. But would much prefer to import it as I do for the other select helpers. 

Thank you! 🕺

**Comment by lionel-** [comment] 2020-08-27 06:55
Duplicate of #208.

**Closed by lionel-** 2020-08-27 06:55 UTC
