### ISSUE TITLE
tidyselect does not export `where`

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/tidyselect#213] opened 2020-09-16 04:44 UTC
I am writing an R package that imports various tidyselect functions. I noticed I can import almost all select helpers like `all_of`, but I cannot import `where` (it's not exported in namespace). My use case is to use it with `dplyr::mutate(where(...))`

**Comment by lionel-** [comment] 2020-09-16 06:12
Duplicate of #209.

We'll export in the next release. You don't need to import it to use it though, just use `utils::globalVariables("where")` in the meantime.

**Closed by lionel-** 2020-09-16 06:12 UTC
