### ISSUE TITLE
Please consider exporting `where()`

### ISSUE THREAD

**Issue by MattCowgill** [r-lib/tidyselect#240] opened 2021-05-17 23:00 UTC
It would be nice to be able to use `tidyselect::where()` in functions in other packages. It does not currently appear to be exported.

**Comment by lionel-** [comment] 2021-05-18 07:33
Duplicate of #201.

tidyselect is a domain-specific language that is specially interpreted. This means `where()` is not a real function and you can use it in your package without a namespace qualifier. Just use `utils::globalVariables("where")` to avoid a note. We'll export it in the next version to make this more intuitive.

**Closed by lionel-** 2021-05-18 07:33 UTC

**Comment by MattCowgill** [comment] 2021-05-18 07:48
OK, thank you for clarifying.
